### PR TITLE
Fix selection of apxs

### PR DESCRIPTION
**Pull request by zippy1981**
Current version was completely broken.

### CODE REVIEW

**Comment by zippy1981** [comment]
I think its better to go with a battle tested macro than a home grown one.

**Comment by jeffreyhorner** [comment]
Agreed. Have you tested on ubuntu at all?

**Comment by zippy1981** [comment]
I'll spin up a VM and check

**Comment by piersharding** [comment]
Hi - I've tested the build of this on Ubuntu 14.04

**Pull request merged**
